name: Expression functions demo

on:
  push:
    branches:
      - master
  issues:
    types: [opened, labeled]


jobs:
  expression-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if string contains substring
        if: contains('Hello world', 'llo')
        run: echo 'True'
      - name: Check if string starts with
        if: startsWith('Hello world', 'He')
        run: echo "true"
      - name: Check if string ends with
        if: endsWith('Hello world', 'ld')]
        run: echo "true"
      - name: Format and echo string
        run: echo ${{ format('Hello {0} {1} {2}', 'James', 'nice', 'to meet') }}
      - name: Join issue labels
        if: github_event_name == 'issues']
        run: echo "Issue labels ${{ join(github.event.issue.labels.*.name, ', ') }}"
      - name: Convert job context to JSON
        run: "echo \"Job context in JSON: ${{ toJSON(github.job) }}\""
      - name: Parse JSON string
        run: "echo \"Parsed JSON: ${{ fromJSON('{"hello":"world"}').hello }}\""
      - name: Hash files
        run: "echo \"Hash of files: ${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}\""
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "Success"
      - name: The job has failed
        if: ${{ failure() }}
        run: echo "Failure"
        
    