on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
      greeting:
        description: "Type of greeting"
        required: true
        type: string
      data:
        description: 'Base64 encoded file string' 
        required: false
        type: string


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Decode file content
        run: |
          echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt
      - name: Dusplay greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"
      - name: Display file content
        run: |
          echo "Content of the file:"
          cat ./decoded_file.txt

# run via Github page
# run via gh cli: gh workflow run manual.yml -f name=James -f greeting=Hello -f data=aGVsbG8gd29ybGQ=